version: 2.1

orbs:
  orb-tools: circleci/orb-tools@2.0.2
  cli: circleci/circleci-cli@0.1.2

jobs:
  validate:
    executor: cli/default
    steps:
    - checkout
    - orb-tools/validate:
        orb-path: ./src/do-exclusively.yml

workflows:
  test:
    jobs:
    - validate
  publish:
    jobs:
    - orb-tools/publish:
        filters:
          tags:
            only: /\d+\.\d+\.\d+/
          branches:
            ignore: /.*/
        orb-path: src/do-exclusively.yml
        orb-ref: miyajan/do-exclusively@${CIRCLE_TAG}
        publish-token-variable: ${ORB_PUBLISHING_TOKEN}
        validate: true
        checkout: true
